env:
  global:
    - secure: "oE2YVQUXTeu+Ra9aUayCSI/ymDwDJJ+MinZcYIJmfNR1hHYRA6PnjkfOqSe1j/t4t/4s6S0UfM07u2xDeAEk4Vhlk18/AaPSpIugIT8aGQ7+/xC+xYRLXAh3R/03POLYe9+HAxTJ5GLShFvOO6A90dqxWizSqZRaTsez4yG09EXtaopGDHLE4ez7e46v9RycPgBLlK6iM2R6BoqWWly3rX/8+HidDZh9P2HndTrH5FuIf0+VcMJ15IHLrxGTIy9FmS5wnVsv+u0Nu7ipL61fbCugBqk/pyd8GbX3qGBP3wtz06jGMn6gemIwxbsVqzjygMBGekHHDIFthDa2SQm1ImW56222EnFZ1OHUP+8TalWGR/7VUK2OpOWFn1GbUrNx4iNo/5PHeM4jCan8vy+ObPSmtNpBa/0CLlx9wqag9lHciTF9oMmvHGn+2YLxX1k8FMFdNWmX/zrWyZH0JgStUWYxJPChWtM+u3yaxOs2fYkk2egzAGjs0c2DB6OUn/wqzWAVGGE5AQhwFMuME+sW97pr+pHD2SWCXzThH99fB7iaN4m8peAqcQlDN/OEsKrBObumjJcJ5v/OXUfx1rWyP38WO+xcRBXKuk8itX/1PfLJBlY+udwq7px1nqc653JM6ZSw1GzQ+K9vWp7Yew4u1NFAFdKXh8kRs4F6WiU3ZOU="
    - secure: "YGchjSWIb7ejG29BU5lhD3kwpS01onQ59C3yKwFzMm9U1JJOSpG+UCbdGQ0HFywvglOxiK43ELBnmqUkUzJcY1QfXjFtErd7G+qUQUtQAEhO2UGx69Z8daag7iA8km1GW48aHaVZ0y7VmrHmWinKxkgg5RsBJNBrsB2hM4A4o7XsBz9/+TkqTr06vbeS+GiDym4MXoo1Sp59CrgbZTc1027goyY8FvXLcf+/nyIXzUCqCWYN5qvMKo/aaHRrzKnpZ+y6wRbCWztqd7oT3EUmdV4Qg9dzUafW+PHDmRJuPXJwrTJAVCLAq03zL5s6UhBd78jQ+PR10XtY/AGDlXoVOi0qzfwvcHsZ0+G9L2DAyUKD9+3XZgaaw2G7xSNpicx9AQ5tzvBfhe5MuK3/uIBdHGKeXqBHkuQUvGt+HeX6EWMVmfkjYFs5jS+N9ZtvUTEkRhIWZtMvsLMgwfQSS9y4lzcdeIwCDyAz2UFIoxyaU8kVNkdPuhOBm9UDjO65an1rBDc1PyMqvXJ4A81nutg8Hps6kiuGpOV4FkDrnghRUVG52R1c1ppur4wfer6uOehBnPp37ksxBZUI8Pmg+/mE0fU8iwt7Bz9YrmOeDbMjUsLBh4XgW6OvZBQGRQ79pwfgSY7OH46cbBciG9tYb7LMfx7l0zebqha/rIrejHdIAK8="

language: java
jdk:
  - openjdk8

branches:
  only:
  - master

before_install:
  - chmod +x gradlew

after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew uploadArchives -PmavenUser=$MAVEN_USER -PmavenPassword=$MAVEN_PASSWORD; fi'

notifications:
  email: false